export type Id = string;

export {
  googleLoginSchema,
  loginSchema,
  registerSchema,
  updateProfileSchema,
  catalogCategorySchema,
  catalogProductSchema,
  createOrderItemSchema,
  createOrderSchema,
  orderResponseSchema,
  adminProductPayloadSchema,
  adminProductResponseSchema,
  adminUserResponseSchema,
  updateUserRoleSchema,
  catalogCategoriesSchema,
  catalogProductsSchema,
  orderResponsesSchema,
  adminProductResponsesSchema,
  adminUserResponsesSchema,
  authUserSchema,
  authResponseSchema,
} from "./schemas/auth.js";

export type {
  GoogleLoginInput,
  LoginInput,
  RegisterInput,
  AuthUser,
  UpdateProfileInput,
  CatalogCategory,
  CatalogProduct,
  CreateOrderItemInput,
  CreateOrderInput,
  OrderResponse,
  AdminProductPayload,
  AdminProductResponse,
  AdminUserResponse,
  UpdateUserRolePayload,
  AuthResponse,
} from "./schemas/auth.js";
